name: MenuMetaMod

main: com.shawlyne.mc.MenuMetaMod.MenuMetaMod

version: 0.4

commands:
    menu:
        description: Player specific menu response commands
        usage: /menu
    quick:
        description: Launch config specified menu
        usage: /quick [Menu.command from config file]