name: MenuMetaMod

main: com.shawlyne.mc.MenuMetaMod.MenuMetaMod

version: 0.4

commands:
    menu:
        description: Player specific menu response commands
        usage: /menu
    m:
        description: Launch config specified menu
        usage: /m <Menu.command from config file>